apiVersion: apps/v1
kind: Deployment
metadata:
  name: conrepo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conrepo
  template:
    metadata:
      labels:
        app: conrepo
    spec:
      containers:
      - name: conrepo
        image: condev08.azurecr.io/conrepo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          runAsUser: 1000
      
---
apiVersion: v1
kind: Service
metadata:
  name: ciceconrepo-svc
spec:
  type: LoadBalancer  # Added LoadBalancer type
  ports:
  - port: 8088
    targetPort: 8080
  selector:
    app: conrepo
